### ISSUE TITLE
route-switching异常数据如何生成的？

### ISSUE THREAD

**Issue by dadqad** [ChenhaoWang2000/UA-OATD#2]

**Comment by dadqad** [comment]
请问route-switching异常数据如何生成的，代码里面好像没有找到相关实现，是否是直接使用[data_generator.py](https://github.com/liuyiding1993/ICDE2020_GMVSAE/blob/master/data_generator.py)进行生成？

**Comment by ChenhaoWang2000** [comment]
你好，route-switching数据生成采用了GM-VSAE的代码，我个人认为他的生成方式有些问题，但是为了与baseline比较仍然采用了他的代码，在data_generator.py没有相关部分
